#ifndef BSW_UDS_UDS_CONFIG_H_
#define BSW_UDS_UDS_CONFIG_H_

//Serial Number / Version
#define DID_F190_VIN_NUMBER "2NIVERSECAR123456"

#define DID_F18C_ECU_SERIAL_NUMBER "INFTC375"

#define DID_F18A_SUPPLIER_ID "2NIVERSE"

#define DID_F193_HW_VERSION "HW_V1.02"

#define DID_F195_SW_VERSION "SW_V2.03"

#endif /* BSW_UDS_UDS_CONFIG_H_ */
